"""Emit README.md documenting the generated project."""
from __future__ import annotations

from pathlib import Path


def emit_readme(out_dir: Path, counts: dict[str, int], envs: list[str],
                kv: str, unresolved: list[str],
                generic_types: list[str] | None = None,
                excluded: list[str] | None = None) -> None:
    out_dir = Path(out_dir)
    lines = ["# Auth0 Terraform Project", "",
             "Generated by the auth0-terraform skill.", "",
             "## Imported resources", ""]
    for tf_type, n in sorted(counts.items()):
        lines.append(f"- `{tf_type}`: {n}")
    lines += ["", "## Environments", ""]
    for env in envs:
        lines.append(f"- `envs/{env}/`")
    lines += [
        "", "## Initialize an environment", "",
        "```bash",
        "cd envs/<env>",
        "terraform init   # configure backend.tf first",
        "terraform plan",
        "```",
        "",
        "## Secrets",
        "",
    ]
    if kv == "azure":
        lines += [
            "Input secrets are read from Azure Key Vault by `secrets.tf`.",
            "Create one secret per resource using the convention "
            "`auth0-<resource-key>-secret`.",
        ]
    else:
        lines += [
            "Input secrets are read from AWS Secrets Manager by `secrets.tf`.",
            "Create one secret per resource using the convention "
            "`auth0/<resource-key>/secret`.",
        ]
    lines += [
        "",
        "Auth0-generated credentials (client_id, client_secret, signing secrets) "
        "are NOT injected and NOT exposed as outputs — they are owned by Auth0 and "
        "live in the Terraform state file after the first apply.",
    ]
    if excluded:
        lines += [
            "", "## Excluded — auto-provisioned by Auth0", "",
            "These resources are created automatically in every Auth0 tenant, so "
            "they are intentionally NOT replicated (managing them would be "
            "redundant and would conflict with the tenant's built-in resources):",
        ]
        lines += [f"- {e}" for e in excluded]
    if generic_types:
        lines += [
            "", "## Generically handled — review", "",
            "These resource types were emitted via the generic for_each path "
            "(no curated mapping). Review the generated `.tf`, variable schema, "
            "and tfvars for correct naming and structure:",
        ]
        lines += [f"- `{t}`" for t in sorted(generic_types)]
    if unresolved:
        lines += ["", "## Manual review needed", "",
                  "These source IDs could not be rewired to references:"]
        lines += [f"- `{u}`" for u in unresolved]
    (out_dir / "README.md").write_text("\n".join(lines) + "\n")
