from auth0tf.secrets import classify_field, COMPUTED_FIELDS


def test_computed_client_secret_is_computed():
    assert classify_field("auth0_client", "client_secret") == "computed"


def test_resource_server_signing_secret_is_computed():
    assert classify_field("auth0_resource_server", "signing_secret") == "computed"


def test_connection_client_secret_is_input():
    # social/enterprise connection secret is something we supply
    assert classify_field("auth0_connection", "client_secret") == "input"


def test_non_secret_field_is_plain():
    assert classify_field("auth0_client", "app_type") == "plain"


def test_token_named_field_is_input_secret():
    assert classify_field("auth0_connection", "api_token") == "input"


def test_client_id_is_computed():
    # client_id is generated by Auth0 in the new tenant — never set it
    assert classify_field("auth0_client", "client_id") == "computed"


def test_computed_registry_shape():
    assert ("auth0_client", "client_secret") in COMPUTED_FIELDS


def test_client_credentials_secret_is_computed_not_input():
    # Auth0 owns the client_credentials secret; it sits in state, not KV.
    assert classify_field("auth0_client_credentials", "client_secret") == "computed"


def test_token_dialect_is_plain_not_secret():
    # token_dialect contains "token" but is a plain enum, not a secret.
    assert classify_field("auth0_resource_server", "token_dialect") == "plain"
